link1: "https://www.railstutorial.org/"
link2: "https://www.railstutorial.org/help"
link3: "https://www.railstutorial.org/book"
link4: "https://www.railstutorial.org/contact"
link5: "https://www.michaelhartl.com/"
link6: "https://news.railstutorial.org/"
